from aiogram.fsm.state import State, StatesGroup


class BotStates(StatesGroup):
    waiting_ping = State()
    waiting_fw_safe_ports = State()
    waiting_open_port = State()
    waiting_close_port = State()
    waiting_ban_ip = State()
    waiting_kill_pid = State()
    waiting_service_name = State()
    service_selected = State()
    waiting_download_path = State()
    waiting_backup_path = State()
    waiting_alert_cpu = State()
    waiting_alert_ram = State()
    waiting_alert_disk = State()
    waiting_alert_interval = State()
    waiting_alert_cooldown = State()
    waiting_alert_services = State()
    waiting_firewall_panic_ip = State()
    waiting_log_service = State()
    waiting_log_search = State()
    waiting_f2b_jail_status = State()
    waiting_f2b_ban = State()
    waiting_f2b_unban = State()
    waiting_docker_logs_container = State()
    waiting_docker_compose_path = State()
    waiting_backup_pro_source = State()
    waiting_backup_pro_restore_archive = State()
    waiting_backup_pro_restore_target = State()
    waiting_backup_pro_delete_name = State()
    waiting_backup_pro_download_name = State()
    waiting_add_admin_id = State()
    waiting_remove_admin_id = State()
    terminal_mode = State()
